# Generated by Django 4.1.7 on 2023-04-14 17:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
        ('action', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionToStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('done', models.BooleanField()),
                ('case_num', models.PositiveSmallIntegerField()),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='action.action')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.student')),
            ],
        ),
    ]
