# Generated by Django 4.1.7 on 2023-03-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('academic_number', models.PositiveIntegerField(unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('mid_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('academic_year', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
