# Generated by Django 4.1.7 on 2023-03-29 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='academic_year',
            field=models.PositiveSmallIntegerField(choices=[(4, 4), (5, 5)]),
        ),
    ]
